In [1]:
import torch
import torch.nn as nn

In [21]:
context_length = 7

mask = torch.triu(torch.ones(context_length, context_length), diagonal=1)
mask

tensor([[0., 1., 1., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1., 1.],
        [0., 0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0.]])

In [11]:
seq_len = 5
mask_bool = mask.bool()[:seq_len, :seq_len]
mask_bool

tensor([[False,  True,  True,  True,  True],
        [False, False,  True,  True,  True],
        [False, False, False,  True,  True],
        [False, False, False, False,  True],
        [False, False, False, False, False]])

In [13]:
attn_scores = torch.randn(5, 5)
a = attn_scores.masked_fill_(mask_bool, -torch.inf)
a

tensor([[-1.5088,    -inf,    -inf,    -inf,    -inf],
        [-0.5027,  1.4412,    -inf,    -inf,    -inf],
        [ 3.0950, -1.0400, -0.1753,    -inf,    -inf],
        [-0.1858, -0.2394, -0.8709, -0.0571,    -inf],
        [-0.2676, -1.3365, -0.2241, -0.2046,  0.6377]])

In [14]:
a.softmax(dim=-1)

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1252, 0.8748, 0.0000, 0.0000, 0.0000],
        [0.9488, 0.0152, 0.0360, 0.0000, 0.0000],
        [0.2786, 0.2641, 0.1404, 0.3169, 0.0000],
        [0.1688, 0.0579, 0.1763, 0.1797, 0.4173]])

In [22]:
b = torch.masked_fill(attn_scores, mask_bool, value=torch.tensor(float("-inf")))
b

tensor([[-1.5088,    -inf,    -inf,    -inf,    -inf],
        [-0.5027,  1.4412,    -inf,    -inf,    -inf],
        [ 3.0950, -1.0400, -0.1753,    -inf,    -inf],
        [-0.1858, -0.2394, -0.8709, -0.0571,    -inf],
        [-0.2676, -1.3365, -0.2241, -0.2046,  0.6377]])